# Generated by Django 3.2.5 on 2021-07-11 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='created_by', editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, db_column='updated_by', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('ticker', models.CharField(db_column='ticker', db_index=True, max_length=10, verbose_name='Ticker')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'db_table': 'entity',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='created_by', editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, db_column='updated_by', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('title', models.CharField(db_column='title', max_length=250, verbose_name='Title')),
                ('link', models.URLField(db_column='link', verbose_name='Link')),
                ('guid', models.UUIDField(db_column='guid', verbose_name='Guid')),
                ('description', models.TextField(db_column='description', verbose_name='Description')),
                ('pub_date', models.DateTimeField(db_column='pub_date', verbose_name='Publication date')),
                ('region', models.CharField(db_column='region', max_length=255, verbose_name='Region')),
                ('entity', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.DO_NOTHING, to='fn_scraping.entity', verbose_name='Entity')),
            ],
            options={
                'verbose_name': 'Financial News',
                'verbose_name_plural': 'Financial News',
                'db_table': 'news',
                'unique_together': {('guid', 'entity', 'region')},
            },
        ),
    ]
